/**
 * Product Display Helpers
 *
 * Auto-generated by PhantomWP
 *
 * Pure display/formatting helpers shared by server code and client scripts.
 * Client-side code must import from THIS module, not from ./woocommerce
 * (which contains the server-only API client).
 */

import { storeConfig } from '../config/store';
import type { WCProduct, WCProductPrices } from './woocommerce';

type PriceInput = string | number | WCProduct | WCProductPrices;

/**
 * Format price with currency
 * Uses product.prices if available (Store API), otherwise falls back to manual formatting
 * @param price - Price string or product object
 * @param currencyOrProduct - Currency code or product for Store API prices
 * @param locale - Locale for formatting (default: en-US)
 */
export function formatPrice(
    price: PriceInput,
    currencyOrProduct: string | WCProduct = '',
    locale: string = 'en-US'
): string {
    const formatStoreAmount = (amount: string, prices: WCProductPrices): string => {
        if (!amount) return '';

        const minorUnit = prices.currency_minor_unit || 2;
        const value = parseInt(amount, 10);
        if (isNaN(value)) return '';

        const decimalValue = value / Math.pow(10, minorUnit);
        const [integerPart, fractionPart] = decimalValue.toFixed(minorUnit).split('.');
        const thousands = prices.currency_thousand_separator ?? ',';
        const decimal = prices.currency_decimal_separator ?? '.';
        const groupedInteger = integerPart.replace(/\B(?=(\d{3})+(?!\d))/g, thousands);
        const number = fractionPart !== undefined && minorUnit > 0
            ? `${groupedInteger}${decimal}${fractionPart}`
            : groupedInteger;

        // Marca: precio en dólares ($) como en el catálogo original de Peptidos Plus.
        const prefix = '$';
        const suffix = '';

        return `${prefix}${number}${suffix}`;
    };

    const formatStorePrices = (prices: WCProductPrices): string => {
        if (prices.price_range) {
            const min = formatStoreAmount(prices.price_range.min_amount, prices);
            const max = formatStoreAmount(prices.price_range.max_amount, prices);
            if (min && max && min !== max) return `${min} - ${max}`;
            return min || max;
        }

        return formatStoreAmount(prices.price, prices);
    };

    // If passed a product directly, format from structured Store API prices.
    // Avoid product.price_html here: WooCommerce includes HTML entities and
    // screen-reader text there, which Astro escapes when rendered as text.
    if (typeof price === 'object' && 'prices' in price) {
        const product = price;
        if (product.prices) {
            return formatStorePrices(product.prices);
        }
    }

    if (typeof price === 'object' && 'currency_code' in price) {
        return formatStorePrices(price);
    }

    // Standard formatting for string/number prices
    const numericPrice = typeof price === 'string' ? parseFloat(price) : (typeof price === 'number' ? price : 0);
    if (isNaN(numericPrice)) return '';

    if (typeof currencyOrProduct === 'object' && currencyOrProduct.prices) {
        const minorUnit = currencyOrProduct.prices.currency_minor_unit || 2;
        const minorAmount = Math.round(numericPrice * Math.pow(10, minorUnit)).toString();
        const storePrice = formatStoreAmount(minorAmount, currencyOrProduct.prices);
        if (storePrice) return storePrice;
    }

    const currency = typeof currencyOrProduct === 'string'
        ? currencyOrProduct
        : currencyOrProduct.prices?.currency_code || storeConfig.currency;

    if (!currency) {
        return numericPrice.toFixed(2);
    }

    return new Intl.NumberFormat(locale, {
        style: 'currency',
        currency,
    }).format(numericPrice);
}

/**
 * Get the main product image URL
 * Store API provides: src (full), thumbnail
 */
export function getProductImageUrl(product: WCProduct, size: 'thumbnail' | 'medium' | 'large' | 'full' = 'full'): string | null {
    const image = product.images?.[0];
    if (!image) return null;

    // Store API returns thumbnail and src (full)
    if (size === 'thumbnail' && image.thumbnail) {
        return image.thumbnail;
    }

    // Return full size image
    return image.src || null;
}

/**
 * Check if product is in stock
 * Uses Store API is_in_stock first, falls back to normalized stock_status
 */
export function isInStock(product: WCProduct): boolean {
    // Store API field (preferred)
    if (typeof product.is_in_stock === 'boolean') {
        return product.is_in_stock && (product.is_purchasable !== false);
    }
    // Normalized field (backwards compat)
    return product.stock_status === 'instock' && product.purchasable !== false;
}

/**
 * Get discount percentage
 */
export function getDiscountPercentage(product: WCProduct): number | null {
    if (!product.on_sale) return null;

    // Try normalized prices first
    let regular = parseFloat(product.regular_price || '');
    let sale = parseFloat(product.sale_price || '');

    // Fall back to prices object from Store API
    if (isNaN(regular) || isNaN(sale) || regular === 0) {
        if (!product.prices) return null;
        const minorUnit = product.prices.currency_minor_unit || 2;
        regular = parseInt(product.prices.regular_price, 10) / Math.pow(10, minorUnit);
        sale = parseInt(product.prices.sale_price, 10) / Math.pow(10, minorUnit);
    }

    if (isNaN(regular) || isNaN(sale) || regular === 0) return null;

    return Math.round(((regular - sale) / regular) * 100);
}

/**
 * Decode HTML entities in text (e.g. &amp; -> &, &lt; -> <)
 */
export function decodeEntities(text: string): string {
    if (!text) return '';
    return text
        .replace(/&#(\d+);/g, (_, code) => String.fromCharCode(parseInt(code, 10)))
        .replace(/&#x([0-9a-fA-F]+);/g, (_, code) => String.fromCharCode(parseInt(code, 16)))
        .replace(/&amp;/g, '&')
        .replace(/&lt;/g, '<')
        .replace(/&gt;/g, '>')
        .replace(/&quot;/g, '"')
        .replace(/&#0?39;/g, "'")
        .replace(/&nbsp;/g, ' ');
}

/**
 * Strip HTML from description
 */
export function stripHtml(html: string): string {
    if (!html) return '';
    return html
        .replace(/<[^>]+>/g, '')
        .replace(/&#(\d+);/g, (_, code) => String.fromCharCode(parseInt(code, 10)))
        .replace(/&#x([0-9a-fA-F]+);/g, (_, code) => String.fromCharCode(parseInt(code, 16)))
        .replace(/&nbsp;/g, ' ')
        .replace(/&amp;/g, '&')
        .replace(/&lt;/g, '<')
        .replace(/&gt;/g, '>')
        .replace(/&quot;/g, '"')
        .replace(/&#39;/g, "'")
        .replace(/\s+/g, ' ')
        .trim();
}

/**
 * Truncate text with ellipsis
 */
export function truncate(text: string, maxLength: number = 150): string {
    if (!text) return '';
    const stripped = stripHtml(text);
    if (stripped.length <= maxLength) return stripped;
    return stripped.substring(0, maxLength).trim() + '...';
}
