/**
 * WooCommerce REST API Client for Astro
 * 
 * Auto-generated by PhantomWP
 * 
 * IMPORTANT: Configure your WooCommerce store URL in .env file:
 *   WP_API_URL=https://your-wordpress-site.com/wp-json
 *   WP_ACCESS_SECRET=your_secret_key
 * 
 * This client fetches products at build time for static generation.
 * For cart/checkout operations, see the cart-store and API routes.
 */

// Get WordPress/WooCommerce API config from environment variables.
// WC_* names are kept as legacy fallbacks, but PhantomWP Connect uses WP_ACCESS_SECRET.
const WC_API_URL = import.meta.env.WP_API_URL || import.meta.env.WC_API_URL || '';
const WP_ACCESS_SECRET = import.meta.env.WP_ACCESS_SECRET || import.meta.env.WC_ACCESS_SECRET || '';

// Warn if using HTTP in production (credentials would be sent in plaintext)
if (WC_API_URL && WC_API_URL.startsWith('http://') && !import.meta.env.DEV) {
    console.error('\x1b[31m%s\x1b[0m', '='.repeat(60));
    console.error('\x1b[31m%s\x1b[0m', 'SECURITY WARNING: WP_API_URL uses HTTP');
    console.error('\x1b[31m%s\x1b[0m', '='.repeat(60));
    console.error('\x1b[33m%s\x1b[0m', 'API credentials are being sent over an unencrypted connection.');
    console.error('\x1b[33m%s\x1b[0m', 'Change WP_API_URL to use HTTPS in production.');
    console.error('\x1b[31m%s\x1b[0m', '='.repeat(60));
}

// ============================================================================
// Types - Store API Response Format
// ============================================================================

export interface WCProductImage {
    id: number;
    src: string;
    thumbnail: string;
    srcset: string;
    sizes: string;
    name: string;
    alt: string;
}

export interface WCProductCategory {
    id: number;
    name: string;
    slug: string;
}

export interface WCProductTag {
    id: number;
    name: string;
    slug: string;
}

export interface WCProductAttribute {
    id: number;
    name: string;
    taxonomy: string;
    has_variations: boolean;
    terms: Array<{ id: number; name: string; slug: string }>;
}

export interface WCProductPrices {
    price: string;
    regular_price: string;
    sale_price: string;
    price_range: { min_amount: string; max_amount: string } | null;
    currency_code: string;
    currency_symbol: string;
    currency_minor_unit: number;
    currency_decimal_separator: string;
    currency_thousand_separator: string;
    currency_prefix: string;
    currency_suffix: string;
}

/**
 * WooCommerce Store API Product Format
 * Note: This differs from REST API v3 format
 */
export interface WCProduct {
    id: number;
    name: string;
    slug: string;
    parent: number;
    type: 'simple' | 'variable' | 'grouped' | 'external';
    variation: string;
    permalink: string;
    sku: string;
    short_description: string;
    description: string;
    on_sale: boolean;
    prices: WCProductPrices;
    price_html: string;
    average_rating: string;
    review_count: number;
    images: WCProductImage[];
    categories: WCProductCategory[];
    tags: WCProductTag[];
    attributes: WCProductAttribute[];
    variations: Array<{ id: number; attributes: Array<{ name: string; value: string }> }>;
    has_options: boolean;
    is_purchasable: boolean;
    is_in_stock: boolean;
    is_on_backorder: boolean;
    low_stock_remaining: number | null;
    sold_individually: boolean;
    add_to_cart: {
        text: string;
        description: string;
        url: string;
        minimum: number;
        maximum: number;
        multiple_of: number;
    };
    // Normalized fields (added by our helper)
    price?: string;
    regular_price?: string;
    sale_price?: string;
    stock_status?: 'instock' | 'outofstock' | 'onbackorder';
    purchasable?: boolean;
    featured?: boolean;
    rating_count?: number;
    related_ids?: number[];
    date_created?: string;
}

export interface WCProductVariation {
    id: number;
    sku: string;
    price: string;
    regular_price: string;
    sale_price: string;
    on_sale: boolean;
    purchasable: boolean;
    stock_status: 'instock' | 'outofstock' | 'onbackorder';
    stock_quantity: number | null;
    image: WCProductImage;
    attributes: Array<{ id: number; name: string; option: string }>;
}

export interface WCCategory {
    id: number;
    name: string;
    slug: string;
    parent: number;
    description: string;
    count: number;
    image: WCProductImage | null;
}

// ============================================================================
// Fetch Helper
// ============================================================================

/**
 * Build headers for WooCommerce API requests
 * Includes the secret header for authenticated server-side requests
 */
function buildHeaders(): Record<string, string> {
    const headers: Record<string, string> = {
        'Accept': 'application/json',
    };
    
    if (WP_ACCESS_SECRET) {
        headers['X-PhantomWP-Secret'] = WP_ACCESS_SECRET;
    }
    
    return headers;
}

/**
 * Generic WooCommerce API fetch helper
 * Uses the WooCommerce Store API (public) for product data
 */
async function wcFetch<T>(
    endpoint: string, 
    params: Record<string, any> = {}, 
    defaultValue?: T
): Promise<T> {
    // Check if WP_API_URL/WC_API_URL is properly configured
    if (!WC_API_URL || !WC_API_URL.startsWith('http')) {
        console.warn(`[WooCommerce] Skipping API call to ${endpoint} - WP_API_URL not configured`);
        return defaultValue as T;
    }
    
    let url: URL;
    try {
        url = new URL(`${WC_API_URL}/wc/store/v1/${endpoint}`);
    } catch (e) {
        console.error(`[WooCommerce] Invalid API URL: ${WC_API_URL}`);
        return defaultValue as T;
    }
    
    Object.entries(params).forEach(([key, value]) => {
        if (value !== undefined && value !== null) {
            if (Array.isArray(value)) {
                url.searchParams.set(key, value.join(','));
            } else {
                url.searchParams.set(key, String(value));
            }
        }
    });
    
    try {
        const response = await fetch(url.toString(), {
            headers: buildHeaders(),
        });
        
        if (!response.ok) {
            console.error(`WooCommerce API error: ${response.status} ${response.statusText}`);
            return defaultValue as T;
        }
        
        return response.json();
    } catch (error) {
        console.error(`WooCommerce API connection failed for ${endpoint}:`, error instanceof Error ? error.message : error);
        return defaultValue as T;
    }
}

/**
 * Fetch from PhantomWP Connect WooCommerce bridge for data that the public
 * Store API does not expose.
 */
async function wcConnectFetch<T>(
    endpoint: string, 
    params: Record<string, any> = {}, 
    defaultValue?: T
): Promise<T> {
    // Check if WP_API_URL/WC_API_URL is properly configured
    if (!WC_API_URL || !WC_API_URL.startsWith('http')) {
        console.warn(`[WooCommerce] Skipping REST API call to ${endpoint} - WP_API_URL not configured`);
        return defaultValue as T;
    }
    
    let url: URL;
    try {
        url = new URL(`${WC_API_URL}/phantomwp/v1/woocommerce/${endpoint}`);
    } catch (e) {
        console.error(`[WooCommerce] Invalid API URL: ${WC_API_URL}`);
        return defaultValue as T;
    }
    
    Object.entries(params).forEach(([key, value]) => {
        if (value !== undefined && value !== null) {
            if (Array.isArray(value)) {
                url.searchParams.set(key, value.join(','));
            } else {
                url.searchParams.set(key, String(value));
            }
        }
    });
    
    try {
        const response = await fetch(url.toString(), { headers: buildHeaders() });
        
        if (!response.ok) {
            console.error(`PhantomWP Connect WooCommerce error: ${response.status} ${response.statusText}`);
            return defaultValue as T;
        }
        
        return response.json();
    } catch (error) {
        console.error(`PhantomWP Connect WooCommerce connection failed for ${endpoint}:`, error instanceof Error ? error.message : error);
        return defaultValue as T;
    }
}

// ============================================================================
// Product Normalizer
// ============================================================================

/**
 * Convert Store API price (in minor units) to decimal string
 */
function normalizePrice(price: string, minorUnit: number): string {
    if (!price) return '';
    const value = parseInt(price, 10);
    if (isNaN(value)) return price;
    return (value / Math.pow(10, minorUnit)).toFixed(2);
}

/**
 * Normalize a Store API product to include backwards-compatible fields
 */
function normalizeProduct(product: WCProduct): WCProduct {
    if (!product) return product;
    
    const minorUnit = product.prices?.currency_minor_unit || 2;
    
    return {
        ...product,
        // Add normalized price fields for backwards compatibility
        price: normalizePrice(product.prices?.price || '', minorUnit),
        regular_price: normalizePrice(product.prices?.regular_price || '', minorUnit),
        sale_price: normalizePrice(product.prices?.sale_price || '', minorUnit),
        // Add normalized stock status
        stock_status: product.is_in_stock ? 'instock' : (product.is_on_backorder ? 'onbackorder' : 'outofstock'),
        purchasable: product.is_purchasable,
        // Featured is not in Store API, default to false
        featured: false,
        rating_count: product.review_count,
    };
}

// ============================================================================
// Products
// ============================================================================

export interface GetProductsOptions {
    page?: number;
    perPage?: number;
    per_page?: number;
    search?: string;
    category?: number;
    tag?: number;
    featured?: boolean;
    onSale?: boolean;
    minPrice?: string;
    maxPrice?: string;
    stockStatus?: 'instock' | 'outofstock' | 'onbackorder';
    orderBy?: 'date' | 'id' | 'title' | 'slug' | 'price' | 'popularity' | 'rating';
    order?: 'asc' | 'desc';
}

/**
 * Get products from WooCommerce
 * Uses Store API for public product data
 */
export async function getProducts(options: GetProductsOptions = {}): Promise<WCProduct[]> {
    const products = await wcFetch<WCProduct[]>('products', {
        page: options.page,
        per_page: options.perPage || options.per_page || 10,
        search: options.search,
        category: options.category,
        tag: options.tag,
        on_sale: options.onSale,
        min_price: options.minPrice,
        max_price: options.maxPrice,
        stock_status: options.stockStatus,
        orderby: options.orderBy || 'date',
        order: options.order || 'desc',
    }, []);
    
    // Normalize all products
    return products.map(normalizeProduct);
}

/**
 * Get all products (paginated fetch)
 */
export async function getAllProducts(): Promise<WCProduct[]> {
    const allProducts: WCProduct[] = [];
    let page = 1;
    let hasMore = true;
    
    while (hasMore) {
        const products = await getProducts({ page, perPage: 100 });
        allProducts.push(...products);
        hasMore = products.length === 100;
        page++;
        
        // Safety limit
        if (page > 50) break;
    }
    
    return allProducts;
}

/**
 * Get a single product by slug
 */
export async function getProduct(slug: string): Promise<WCProduct | null> {
    const products = await wcFetch<WCProduct[]>('products', { slug }, []);
    if (products && products.length > 0) {
        return normalizeProduct(products[0]);
    }
    return null;
}

/**
 * Get a single product by ID
 */
export async function getProductById(id: number): Promise<WCProduct | null> {
    const product = await wcFetch<WCProduct | null>(`products/${id}`, {}, null);
    return product ? normalizeProduct(product) : null;
}

/**
 * Get product variations (for variable products)
 */
export async function getProductVariations(productId: number): Promise<WCProductVariation[]> {
    return wcConnectFetch<WCProductVariation[]>(`products/${productId}/variations`, { per_page: 100 }, []);
}

/**
 * Get featured products
 */
export async function getFeaturedProducts(limit: number = 8): Promise<WCProduct[]> {
    return getProducts({ featured: true, perPage: limit });
}

/**
 * Get products on sale
 */
export async function getOnSaleProducts(limit: number = 8): Promise<WCProduct[]> {
    return getProducts({ onSale: true, perPage: limit });
}

/**
 * Get related products
 */
export async function getRelatedProducts(product: WCProduct, limit: number = 4): Promise<WCProduct[]> {
    if (!product.related_ids || product.related_ids.length === 0) {
        // Fall back to products in same category
        if (product.categories.length > 0) {
            return getProducts({ category: product.categories[0].id, perPage: limit });
        }
        return [];
    }
    
    // Fetch related products by ID
    const related: WCProduct[] = [];
    for (const id of product.related_ids.slice(0, limit)) {
        const p = await getProductById(id);
        if (p) related.push(p);
    }
    return related;
}

// ============================================================================
// Categories
// ============================================================================

/**
 * Get all product categories
 */
export async function getProductCategories(): Promise<WCCategory[]> {
    return wcFetch<WCCategory[]>('products/categories', { per_page: 100 }, []);
}

/**
 * Get category by slug
 */
export async function getProductCategoryBySlug(slug: string): Promise<WCCategory | null> {
    const categories = await wcFetch<WCCategory[]>('products/categories', { slug }, []);
    return categories && categories.length > 0 ? categories[0] : null;
}

/**
 * Get products by category slug
 */
export async function getProductsByCategory(categorySlug: string): Promise<WCProduct[]> {
    const category = await getProductCategoryBySlug(categorySlug);
    if (!category) return [];
    return getProducts({ category: category.id, perPage: 100 });
}

/**
 * Get top-level categories (no parent)
 */
export async function getTopLevelCategories(): Promise<WCCategory[]> {
    const all = await getProductCategories();
    return all.filter(cat => cat.parent === 0);
}

/**
 * Get child categories for a parent
 */
export async function getChildCategories(parentId: number): Promise<WCCategory[]> {
    const all = await getProductCategories();
    return all.filter(cat => cat.parent === parentId);
}

// ============================================================================
// Helpers
// ============================================================================

// Display/formatting helpers live in ./product-display so client-side code can
// import them without bundling this server-only API client. Re-exported here
// for backwards compatibility with server-side importers.
export {
    formatPrice,
    getProductImageUrl,
    isInStock,
    getDiscountPercentage,
    decodeEntities,
    stripHtml,
    truncate,
} from './product-display';
